Error handling for decimal128 and rprice addition
featuremine/yamal pull request #105
Opened 2022-11-02 21:11 UTC by fm-andres-rangel

2022-11-03 15:08 UTC, maxim-trokhimtchouk requested changes

2022-11-04 13:54 UTC, fm-fede-ravchina submitted a review, later dismissed

2022-11-04 14:49 UTC, maxim-trokhimtchouk approved these changes

2022-11-04 14:49 UTC, maxim-trokhimtchouk commented on include/fmc++/decimal128.hpp
> +    static decimal128 dec64div((int64_t)RPRICE_FRACTION);
needs to be FMC_RPRICE_FRACTION

2022-11-04 20:20 UTC, fm-fede-ravchina approved these changes

2022-11-04 20:20 UTC, merged