Yamal Python
featuremine/yamal pull request #111
Opened 2022-11-08 18:35 UTC by fm-ivang

2022-11-08 19:28 UTC, maxim-trokhimtchouk requested changes

2022-11-08 19:28 UTC, maxim-trokhimtchouk commented on mypy.ini
> +ignore_missing_imports = True
need a new line

2022-11-09 15:00 UTC, fm-fede-ravchina approved these changes

2022-11-09 18:31 UTC, maxim-trokhimtchouk approved these changes

2022-11-09 18:37 UTC, fm-fede-ravchina approved these changes

2022-11-09 18:38 UTC, merged