YTP Closable, Multi-list support and C compilation
featuremine/yamal pull request #157
Opened 2023-06-05 16:27 UTC by fm-fede-ravchina

2023-06-05 21:20 UTC, maxim-trokhimtchouk requested changes

2023-06-05 21:20 UTC, maxim-trokhimtchouk commented on src/ytp/yamal.c
> +struct mmnode {
Move to h file

2023-06-06 15:08 UTC, maxim-trokhimtchouk submitted a review, later dismissed

2023-06-06 15:09 UTC, fm-andres-rangel submitted a review, later dismissed

2023-08-25 15:28 UTC, closed without merging