YTP 8
featuremine/yamal pull request #161
Opened 2023-08-23 20:13 UTC by fm-fede-ravchina

2023-08-24 22:00 UTC, fm-andres-rangel requested changes

2023-08-25 19:59 UTC, maxim-trokhimtchouk commented on include/ytp/sequence.h
> +FMMODFUNC ytp_iterator_t ytp_sequence_seek(ytp_sequence_t *seq, uint64_t offset,
change to ytp_mmnode_offs

2023-08-25 20:02 UTC, maxim-trokhimtchouk commented on src/ytp/api.cpp
> +  ytp_sequence_shared_reserve, ytp_sequence_shared_commit, NULL, NULL,
make ytp_sequence_shared_sub, ytp_sequence_shared_dir, not implemented

2023-08-25 20:06 UTC, maxim-trokhimtchouk requested changes
test syncer built with new ytp connected to syncer built with old ytp and the reverse.
performance test similar to before (yamal-perf, syncer perf, number of messages read per sec)

2023-08-29 18:55 UTC, maxim-trokhimtchouk requested changes

2023-08-29 18:55 UTC, maxim-trokhimtchouk commented on include/ytp/cursor.h
> +FMMODFUNC bool ytp_cursor_term(ytp_cursor_t *cursor, fmc_error_t **error);
maybe removing this

2023-08-29 18:55 UTC, maxim-trokhimtchouk commented on include/ytp/cursor.h
> +FMMODFUNC bool ytp_cursor_poll(ytp_cursor_t *cursor, fmc_error_t **error);
add TODO for ytp_cursor_poll_until

2023-08-29 18:55 UTC, maxim-trokhimtchouk commented on src/ytp/glob.cpp
> +struct ytp_glob {
add a TODO note to properly handle exceptions

2023-08-29 20:41 UTC, maxim-trokhimtchouk submitted a review, later dismissed

2023-08-30 13:15 UTC, fm-andres-rangel submitted a review, later dismissed

2023-08-30 16:53 UTC, fm-andres-rangel approved these changes

2023-08-30 18:48 UTC, fm-andres-rangel approved these changes

2023-08-30 18:55 UTC, merged