Notification mechanisms
featuremine/yamal pull request #31
Opened 2022-08-15 16:06 UTC by fm-andres-rangel

2022-08-15 17:21 UTC, maxim-trokhimtchouk commented on src/fmc/component.c
> +
#define DL_GET_ELEM(head, idx)                                                 \
   ({                                                                           \
     size_t count = (idx);                                                              \
     __typeof__(head) _el = NULL;                                               \
     _el = NULL;                                                                \
       DL_FOREACH(head, _el) {                                                  \
         if (!count--) break;                                                        \
       }                                                                        \
     _el;                                                                       \
   })

2022-08-16 16:31 UTC, maxim-trokhimtchouk requested changes
Fixing component new

2022-08-16 16:31 UTC, maxim-trokhimtchouk commented on src/fmc/component.c
> +    return;
set the reactor error and goto clean up

2022-08-16 19:47 UTC, maxim-trokhimtchouk requested changes

2022-08-16 19:47 UTC, maxim-trokhimtchouk commented on src/fmc/component.c
> +        "failed to notify the component %s: invalid dependency index %lu",
"component type %s updating output using incorrect output index %lu"

2022-08-16 19:47 UTC, maxim-trokhimtchouk commented on src/fmc/component.c
>      new_dep.idx = item->comp->_ctx->idx;
fmc_reactor_ctx_emplace instead of fmc_reactor_ctx_push. We should clear ctx at the end of the function call

2022-08-16 19:47 UTC, maxim-trokhimtchouk commented on src/fmc/component.c
>    if (fmc_error_has(error))
add fmc_reactor_ctx_destroy here

2022-08-16 21:59 UTC, maxim-trokhimtchouk approved these changes

2022-08-16 22:13 UTC, fm-ivang approved these changes

2022-08-16 22:14 UTC, merged