Memory issues fix
featuremine/yamal pull request #39
Opened 2022-08-25 21:00 UTC by fm-ivang

Fix memory errors reported by Valgrind.
Fix compilation warnings.

2022-08-25 21:42 UTC, maxim-trokhimtchouk requested changes
Just delete the commented code. Otherwise good.

2022-08-25 21:42 UTC, maxim-trokhimtchouk commented on include/fmc++/config/variant_map.hpp
> +    // std::get_if<array>(&val_)
We should not have commented code. If that code is not needed, just delete it.

2022-08-26 13:27 UTC, fm-andres-rangel requested changes

2022-08-26 13:34 UTC, fm-andres-rangel commented on include/fmc++/config/variant_map.hpp
> +    } else if (std::get_if<section>(&val_)) {
resolved by https://github.com/featuremine/yamal/pull/39/commits/63b75a9ae10e2aaa41eda6bd2f20ff785c58169e

2022-08-26 13:34 UTC, fm-andres-rangel approved these changes

2022-08-26 14:13 UTC, maxim-trokhimtchouk approved these changes

2022-08-26 14:15 UTC, merged