Decimal support
featuremine/yamal pull request #92
Opened 2022-10-19 14:26 UTC by fm-andres-rangel

2022-10-19 20:25 UTC, fm-fede-ravchina approved these changes

2022-10-20 12:59 UTC, fm-fede-ravchina requested changes

2022-10-20 12:59 UTC, fm-fede-ravchina commented on include/fmc++/decimal128.hpp
> +  }
epsilon is missing

2022-10-20 13:10 UTC, fm-fede-ravchina requested changes

2022-10-20 13:10 UTC, fm-fede-ravchina commented on include/fmc++/decimal128.hpp
> +  decimal128(const fmc_decimal128_t &a) : fmc_decimal128_t(a) {}
we need a default constructor

2022-10-20 18:27 UTC, fm-andres-rangel commented on include/fmc++/decimal128.hpp
> +  decimal128(const fmc_decimal128_t &a) : fmc_decimal128_t(a) {}
Resolved with ba89753

2022-10-20 18:28 UTC, fm-andres-rangel commented on include/fmc++/decimal128.hpp
> +  }
resolved with 6cb7489

2022-10-20 20:56 UTC, maxim-trokhimtchouk submitted a review, later dismissed

2022-10-20 21:16 UTC, fm-ivang approved these changes

2022-10-20 21:21 UTC, maxim-trokhimtchouk approved these changes

2022-10-20 21:22 UTC, merged